app:
  name: ui
  image:
    repository: 'onecx/onecx-iam-ui'
  routing:
    enabled: true
    path: /mfe/iam/
    
  operator:
    # Microfrontend
    microfrontend:
      enabled: true
      spec:
        main:
          exposedModule: "./OneCXIamModule"
          description: "OneCX IAM UI"
          note: "OneCX IAM UI module auto import via MF operator"
          type: MODULE
        change-password:
          exposedModule: "./OneCXChangePasswordComponent"
          description: "Change password"
          type: COMPONENT
    # Permission
    permission:
      enabled: true
      spec:
        permissions:
          USER:
            SEARCH: Search users
            EDIT: Edit users
          ROLE:
            SEARCH: Search roles
    # Keycloak
    keycloak:
      client:
        enabled: true
        spec:
          kcConfig:
            clientId: "onecx-iam-ui"

# PIPE Config
